### ISSUE TITLE
Just an info

### ISSUE THREAD

**Issue by nicolet-98** [astrazeneca-cgr-publications/JARVIS#4]
Hi,
I do not know if this is the correct place to ask this, but I am wondering if the tool could be used to analyze the variants inside VCF files. Does it accept VCFs as input?

Thanks in advance!

**Comment by dvitsios** [comment]
Hi, 
JARVIS will be provided as a pre-calculated score across the entire genome with single nucleotide resolution.
It's been pre-trained based on various features, including also VCF files from TOPMed (>62,000 samples) to have a sufficiently good representation of the MAF spectrum from a large sample.

That means that you'll be able to directly annotate the variants from your VCF file with the JARVIS scores and get a disease-likelihood score for each of them (will be a single score for all three alternative alleles).
We're aiming to make this publicly available soon.
