### ISSUE TITLE
Available for Build 38?

### ISSUE THREAD

**Issue by Phillip-a-richmond** [astrazeneca-cgr-publications/JARVIS#5]
Hasn't the community agreed to move to build GRCh38 (hg38)? 

Will you make this cool resource available there, either through retraining or lifting over?

Thanks,
Phil

**Comment by dvitsios** [comment]
Hi Phil,

thanks for your comment, we're aiming to make the JARVIS and gwRVIS scores available in build GRCh38 as well (through liftover) later this year - hopefully within the next couple of months.

Best,
Dimitris

**Comment by dvitsios** [comment]
We've now added the liftovered versions for the JARVIS and gwRVIS scores (**hg38**) in our public Box repository:

http://jarvis.public.cgr.astrazeneca.com/

Paths: 
- `JARVIS-gwRVIS-scores/hg38/JARVIS` 
- `JARVIS-gwRVIS-scores/hg38/gwRVIS`
