### ISSUE TITLE
Example - JARVIS - SVs prediction

### ISSUE THREAD

**Issue by frequena** [astrazeneca-cgr-publications/JARVIS#9]
Hello @dvitsios,

I have a bed file with structural variants and I would like to get the JARVIS prediction for each variant. I installed JARVIS successfully, and I have tried to follow the README document (https://github.com/astrazeneca-cgr-publications/JARVIS/blob/master/modules/README.md) but, unfortunately, I do not understand how to perform it. I would really appreciate if you can provide a simple example to perform the prediction.

Thank you!!!

**Comment by dvitsios** [comment]
Hi,

you don't need to run the JARVIS model to get the JARVIS scores for the set of structural variants you have. 
These have been pre-generated for the entire genome and you can find them here:
http://jarvis.public.cgr.astrazeneca.com

After you download these, you can just subset the regions of interest - using the `tabix` tool for more efficiency- which will give you directly the JARVIS scores for those regions.

**Comment by frequena** [comment]
Perfect @dvitsios 

I am going to do that.

Thank you very much for your **really** quick response!!
